### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by EmilMoe** [thepinecode/policy#6]
I can see there hasn't been done any changes to the code in 2 years, and composer.json in 14 months. Is this project still alive? These numbers make me afraid to start implementing it.

**Comment by iamgergo** [comment]
Hi!

Well, yes we don't really maintain this project anymore.

The main reason behind is the stack we used to develop with changed – now we use Inertia for nearly all the projects. It means we can easily do all the authorization process on the back-end, which is the best, since it's native.

I'm going to archive this project, but feel free to fork it or create your own package using anything from this code.

Thanks!
